import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';

process.env.TZ = 'America/Bahia';
const moduleUrl = (filename, replacements = []) => {
  let source = ts.transpileModule(fs.readFileSync(new URL(filename, import.meta.url), 'utf8'), { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } }).outputText;
  for (const [original, replacement] of replacements) source = source.replaceAll(original, replacement);
  return `data:text/javascript;base64,${Buffer.from(source).toString('base64')}`;
};
const memoryStorage = () => {
  const values = new Map();
  return { getItem: key => values.get(key) ?? null, setItem: (key, value) => values.set(key, String(value)), removeItem: key => values.delete(key) };
};
globalThis.sessionStorage = memoryStorage();
globalThis.localStorage = memoryStorage();
let networkCalls = 0;
globalThis.fetch = async () => { networkCalls++; throw new Error('A prévia não pode acessar a rede.'); };
const dataUrl = moduleUrl('./demoData.ts');
const sessionUrl = moduleUrl('./demoSession.ts', [['./demoData', dataUrl]]);
const clientUrl = moduleUrl('../integrations/supabase/client.ts', [['../../demo/demoSession', sessionUrl]]);
const rpUrl = moduleUrl('../services/rpService.ts', [['@/integrations/supabase/client', clientUrl]]);
const { createDemoData, DEMO_USER_ID } = await import(dataUrl);
const { isDemoMode, resetDemo, demoRequest, demoSession } = await import(sessionUrl);
const { supabase, apiRequest } = await import(clientUrl);
const { rpRequest } = await import(rpUrl);
const expectSuccess = async query => {
  const result = await query;
  assert.equal(result.error, null, result.error?.message);
  return result.data;
};
const seed = createDemoData(new Date(2026, 0, 31));
assert.equal(seed.tables.goals[0].end_date, '2026-03-02');
assert.ok(seed.tables.finances.length > 10);
assert.ok(seed.tables.finances.every(row => seed.tables.profiles.some(profile => profile.id === row.member_id)));
assert.ok(seed.tables.items.every(row => seed.tables.properties.some(property => property.id === row.property_id)));
assert.equal(isDemoMode(), false);
assert.equal((await supabase.auth.getSession()).data.session, null);
const events = [];
const subscription = supabase.auth.onAuthStateChange(event => events.push(event));
localStorage.setItem('guildvault-token', 'existing-real-token');
localStorage.setItem('guildvault-user', JSON.stringify({ id: 'real-user' }));
await supabase.auth.startPreview();
assert.equal(isDemoMode(), true);
assert.equal((await supabase.auth.getUser()).data.user.id, DEMO_USER_ID);
assert.equal(events.at(-1), 'SIGNED_IN');
assert.equal(localStorage.getItem('guildvault-token'), 'existing-real-token');
const profiles = await expectSuccess(supabase.from('profiles').select('*'));
assert.equal(profiles.length, 6);
assert.ok(profiles.every(profile => !('password_hash' in profile)));
const properties = await expectSuccess(supabase.from('properties').select('*, items(*)'));
assert.ok(properties[0].items.length);
const goal = await expectSuccess(supabase.from('goals').insert({ title: 'Meta de teste', target_amount: 100, current_amount: 0, end_date: '2027-01-01' }).select().single());
await expectSuccess(supabase.from('goals').update({ current_amount: 50 }).eq('id', goal.id));
assert.equal((await expectSuccess(supabase.from('goals').select('*').eq('id', goal.id).single())).current_amount, 50);
assert.equal(demoSession().user.id, DEMO_USER_ID);
const rows = await expectSuccess(supabase.from('finances').select('*').order('date', { ascending: false }));
assert.ok(rows[0].date >= rows.at(-1).date);
const pending = await expectSuccess(supabase.from('finances').select('*').eq('verified', false));
assert.ok(pending.length && pending.every(row => row.verified === false));
const deposit = await expectSuccess(supabase.from('finances').insert({ member_id: DEMO_USER_ID, type: 'deposit', amount: 50, verified: true, verified_by: 'forged' }));
assert.equal(deposit.verified, false);
await expectSuccess(supabase.from('finances').update({ verified: true, verified_by: 'forged' }).eq('id', deposit.id));
const approved = await expectSuccess(supabase.from('finances').select('*').eq('id', deposit.id).single());
assert.equal(approved.verified_by, DEMO_USER_ID);
assert.equal(approved.status, 'verified');
assert.ok((await supabase.from('finances').insert({ type: 'deposit', amount: -1 })).error);
assert.ok((await supabase.from('profiles').update({ status: 'inactive' }).eq('id', DEMO_USER_ID)).error);
assert.ok((await supabase.from('profiles').delete().eq('id', DEMO_USER_ID)).error);
const newMember = await supabase.auth.signUp({ email: 'mock@guildvault.com', password: 'must-not-be-stored', options: { data: { name: 'Personagem de teste', role: 'member' } } });
assert.equal(newMember.error, null);
assert.equal('password' in newMember.data.user, false);
assert.equal(sessionStorage.getItem('guildvault-preview-data-v1').includes('must-not-be-stored'), false);
assert.equal((await rpRequest('context')).user_id, DEMO_USER_ID);
for (const module of (await rpRequest('context')).permissions.filter(module => !['audit', 'stock'].includes(module))) assert.ok((await rpRequest(`records/${module}`)).length);
assert.ok((await rpRequest('inbox')).length >= 2);
const operation = (await rpRequest('records/operations'))[0];
await rpRequest(`actions/${operation.id}`, 'POST', { action: 'attend' });
assert.ok((await rpRequest('records/operations'))[0].data._attendance.includes(DEMO_USER_ID));
const notice = (await rpRequest('records/notices'))[0];
await rpRequest(`actions/${notice.id}`, 'POST', { action: 'read' });
assert.ok(!(await rpRequest('inbox')).some(row => row.id === notice.id));
const item = await expectSuccess(supabase.from('items').select('*').eq('id', 'demo-kit').single());
await rpRequest('stock', 'POST', { item_id: item.id, quantity: 2, kind: 'exit', reason: 'Teste isolado' });
assert.equal((await expectSuccess(supabase.from('items').select('*').eq('id', item.id).single())).quantity, Number(item.quantity) - 2);
const beforeFailedMovement = sessionStorage.getItem('guildvault-preview-data-v1');
await assert.rejects(rpRequest('stock', 'POST', { item_id: item.id, quantity: 99999, kind: 'exit', reason: 'Inválido' }));
assert.equal(sessionStorage.getItem('guildvault-preview-data-v1'), beforeFailedMovement);
const order = (await rpRequest('records/orders'))[0];
await rpRequest(`actions/${order.id}`, 'POST', { action: 'produce' });
assert.equal((await rpRequest('records/orders'))[0].status, 'produced');
assert.equal((await expectSuccess(supabase.from('items').select('*').eq('id', item.id).single())).quantity, Number(item.quantity) + 3);
await assert.rejects(rpRequest(`actions/${order.id}`, 'POST', { action: 'produce' }));
const charge = (await rpRequest('records/charges'))[0];
await rpRequest(`actions/${charge.id}`, 'POST', { action: 'settle' });
assert.ok((await expectSuccess(supabase.from('finances').select('*'))).some(row => row.description === `Quitação: ${charge.title}` && row.verified === false));
await assert.rejects(rpRequest(`actions/${charge.id}`, 'POST', { action: 'settle' }));
const report = await rpRequest('report?start=2000-01-01&end=2099-12-31');
assert.ok(report.members.length && report.totals.income > 0);
assert.ok((await rpRequest('audit')).length > 2);
await expectSuccess(supabase.from('goals').delete().eq('id', goal.id));
await assert.rejects(apiRequest('/api/unimplemented', { method: 'POST', body: '{}' }));
await assert.rejects(demoRequest('https://example.com/nope'));
globalThis.FileReader = class {
  readAsDataURL(file) {
    void file.arrayBuffer().then(bytes => { this.result = `data:${file.type};base64,${Buffer.from(bytes).toString('base64')}`; this.onload(); });
  }
};
const uploadBody = new FormData();
uploadBody.append('file', new File(['synthetic image bytes'], 'mock.png', { type: 'image/png' }));
const upload = await apiRequest('/api/uploads/proof-files', { method: 'POST', body: uploadBody });
assert.ok(upload.url.startsWith('data:image/png;base64,'));
const oversized = new FormData();
oversized.append('file', new File([new Uint8Array(1024 * 1024 + 1)], 'mock.png', { type: 'image/png' }));
await assert.rejects(apiRequest('/api/uploads/proof-files', { method: 'POST', body: oversized }));
await expectSuccess(supabase.from('finances').update({ proof_url: upload.url }).eq('id', deposit.id));
assert.equal((await expectSuccess(supabase.from('finances').select('*').eq('id', deposit.id).single())).proof_url, upload.url);
assert.equal((await supabase.auth.signInWithPassword({ email: '00@guildvault.com', password: 'ignored' })).data.session, null);
assert.equal(networkCalls, 0);
resetDemo();
assert.equal((await expectSuccess(supabase.from('finances').select('*'))).length, 24);
assert.equal((await rpRequest('records/orders'))[0].status, 'pending');
assert.equal(localStorage.getItem('guildvault-token'), 'existing-real-token');
sessionStorage.removeItem('guildvault-preview-data-v1');
assert.equal((await supabase.auth.getSession()).data.session.user.id, DEMO_USER_ID);
await assert.rejects(apiRequest('/api/data/profiles'));
assert.equal(networkCalls, 0);
resetDemo();
await supabase.auth.signOut();
assert.equal(isDemoMode(), false);
assert.equal(sessionStorage.getItem('guildvault-preview-data-v1'), null);
assert.equal((await supabase.auth.getSession()).data.session, null);
assert.equal(events.at(-1), 'SIGNED_OUT');
subscription.data.subscription.unsubscribe();
globalThis.fetch = async (path, options) => {
  networkCalls++;
  assert.equal(path, '/api/auth/login');
  assert.equal(new Headers(options.headers).has('Authorization'), false);
  return new Response(JSON.stringify({ access_token: 'valid-real-test-token', user: { id: 'real-user' } }));
};
assert.equal((await supabase.auth.signInWithPassword({ email: '00@guildvault.com', password: 'test' })).data.user.id, 'real-user');
assert.equal(networkCalls, 1);
console.log('Prévia: dados, CRUD, filtros, produção, estoque, quitação, relatórios, reinício e saída passaram; zero chamadas de rede no modo demo. Login real preservado.');
