import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const source = fs.readFileSync(new URL('./drivePhysics.ts', import.meta.url), 'utf8');
const js = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ESNext } }).outputText;
const { newDriveState, stepDrive, driveCollides } = await import(`data:text/javascript;base64,${Buffer.from(js).toString('base64')}`);
const simulate = (state, keys, colliders, seconds) => { for (let n = 0; n < seconds * 120; n++) stepDrive(state, new Set(keys), colliders, 1 / 120); };
const state = newDriveState();
assert.equal(driveCollides(0, 0, 0, []), false);
simulate(state, ['forward'], [], 2);
assert(state.speed > 15 && state.z > 10);
assert(Math.abs(state.distance - state.z) < 0.001);
simulate(state, ['brake'], [], 2);
assert.equal(state.speed, 0);
simulate(state, ['backward'], [], 2);
assert(state.speed < 0);
const wall = [{ minX: -12, maxX: 12, minZ: 10, maxZ: 12 }];
const collision = newDriveState(); simulate(collision, ['forward'], wall, 10);
assert(collision.z <= 10 - 2.17 + 0.001, 'car must stop before front bumper reaches wall');
assert.equal(driveCollides(collision.x, collision.z, collision.heading, wall), false);
simulate(collision, ['backward'], wall, 2);
assert(collision.z < 5, 'reverse must escape wall');
const boundary = newDriveState(); simulate(boundary, ['forward'], [], 30);
assert(boundary.z < 178 && boundary.z > 170);
assert.equal(driveCollides(boundary.x, boundary.z, boundary.heading, []), false);
const corner = newDriveState(); simulate(corner, ['forward', 'left'], [], 2);
assert(corner.heading > 0 && corner.x > 0);
const coasting = newDriveState(); simulate(coasting, ['forward'], [], 1); simulate(coasting, [], [], 10);
assert.equal(coasting.speed, 0);
console.log('Drive physics: spawn, acceleration, braking, reverse, wall collision/escape, world boundary, steering and coast passed.');
