import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
process.env.TZ = 'America/Bahia';
const compile = filename => ts.transpileModule(fs.readFileSync(new URL(filename, import.meta.url), 'utf8'), { compilerOptions: { module: ts.ModuleKind.ESNext } }).outputText;
const helperUrl = `data:text/javascript;base64,${Buffer.from(compile('./financeContent.ts')).toString('base64')}`;
const { isPositiveAmount, isCalendarDate, calendarDate, localDate, matchesVerification, transactionSummary } = await import(helperUrl);
for (const value of ['', ' ', 'NaN', 'Infinity', '-3', '0', NaN, Infinity]) assert.equal(isPositiveAmount(value), false);
for (const value of [1, '0.01', '23.5']) assert.equal(isPositiveAmount(value), true);
for (const value of [1e60, '1e60', 1_000_000_001, -1e60]) assert.equal(isPositiveAmount(value), false);
assert.equal(isPositiveAmount(1_000_000_000), true);
for (const value of ['2026-02-29', '2026-04-31', '2026-13-01', '']) assert.equal(isCalendarDate(value), false);
assert.equal(isCalendarDate('2028-02-29'), true);
assert.equal(localDate(calendarDate('2026-10-01')), '2026-10-01');
assert.equal(calendarDate('2026-10-01').getMonth(), 9);
assert.equal(matchesVerification(false, 'pending'), true);
assert.equal(matchesVerification(true, 'pending'), false);
assert.equal(matchesVerification(true, 'verified'), true);
assert.equal(matchesVerification(false, 'all'), true);
assert.deepEqual(transactionSummary([{ type: 'deposit', amount: 20 }, { type: 'withdrawal', amount: 5 }]), { income: 20, expenses: 5, balance: 15 });
assert.deepEqual(transactionSummary([]), { income: 0, expenses: 0, balance: 0 });
const dateFns = await import('date-fns');
const datesJs = compile('./dateFilters.ts').replace('from "date-fns"', 'from "' + new URL('../../node_modules/date-fns/index.js', import.meta.url).href + '"').replace('from "./financeContent"', 'from "' + helperUrl + '"');
const { filterTransactionsByDate } = await import(`data:text/javascript;base64,${Buffer.from(datesJs).toString('base64')}`);
const transactions = [{ id: '1', date: '2026-10-01' }, { id: '2', date: '2026-10-02' }];
const singleDay = { from: new Date(2026, 9, 1), to: new Date(2026, 9, 1) };
assert.deepEqual(filterTransactionsByDate(transactions, 'custom', singleDay), [transactions[0]]);
assert.deepEqual(filterTransactionsByDate(transactions, 'custom', { from: singleDay.from, to: new Date(2026, 8, 1) }), []);
assert.equal(typeof dateFns.startOfDay, 'function');
console.log('Conteúdo financeiro: valores, datas, fuso, status, totais e intervalo inclusivo passaram.');
