
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpjxwuvwtzsyrjjlrlpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wanh3dXZ3dHpzeXJqamxybHBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNDU2NDQsImV4cCI6MjA1OTgyMTY0NH0.uh9NGk1YRzBu-P8hxQMUSNdpwvC-EF5K4ZJBB-bP6Gk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'implicit'
  }
});

// Define custom types for using with supabase
export type Tables = Database['public']['Tables'];
export type ProfileRow = Tables['profiles']['Row'];
export type FinanceRow = Tables['finances']['Row'] & {
  verified_by?: string | null;
  verification_notes?: string | null;
  status?: FinanceStatus;
};
export type GoalRow = Tables['goals']['Row'];
export type PaymentScheduleRow = Tables['payment_schedule']['Row'];

// New finance status enum for improved type checking
export enum FinanceStatus {
  PENDING = 'pending',
  VERIFIED = 'verified',
  REJECTED = 'rejected'
}
